dino_head: 
  out_dim: 65536  # 131072 sometimes good for dinov2, testing is necessary
  norm_last_layer: False
  loss_weight: 1.0
ibot:
  loss_weight: 1.0
  out_dim: 65536 # 131072 sometimes good for dinov2, testing is necessary
  norm_last_layer: False
  mask_sample_probability: 1
  mask_ratio_min_max:
  - 0.3
  - 0.7 
distribution:
  type: 'ddp'  
  mixed_precision: bf16
  downcast_bf16: 'no'
train:
  model_name: 'custom'
  model_type: 'custom'
  global_batch_size: 32
  max_iterations: 60000   
  gradient_checkpointing_enable: false 
  clip_grad: 3.0 
  freeze_last_layer: 100
  warmup_teacher_temp_iterations: 500  
  warmup_iterations: 10000              
  teacher_temp: 0.07
  warmup_teacher_temp: 0.04
  freeze_backbone_layers: 0
  momentum_teacher: 0.9992
  centering: 'centering'
  ibot_separate_head: true
  num_workers: 8            
  use_pretrained: True    
  generate_samples: True  
  PCA_component: 3
  student_temp: 0.1
  center_momentum: 0.9 
  lr: 2e-4
  min_lr: 1e-5
  weight_decay: 0.04
  weight_decay_end: 0.4
  saveckp_freq: 100                     
crops:
  global_crops_scale:
    - 0.7
    - 1.0
  local_crops_number: 4
  global_crops_number: 2
  local_crops_scale:
    - 0.1
    - 0.4
  global_crops_size: 384
  local_crops_size: 112

dataset:
  dataset_path: /home/ge.polymtl.ca/p123239/slice_extractor/resample05
  shuffle: true
  size: 384
output_folders:
  train_checkpoint_dir: train_checkpoints
  teacher_checkpoint_dir: teacher_checkpoints
  training_samples_dir: training_samples
  training_results_dir: training_results
  log_dir: log_files
  main_output: outputs_384
